### ISSUE TITLE
Feature request color scheme pulled from emacs theme

### ISSUE THREAD

**Issue by Dou2ble** [mumu-lhl/eaf-pyqterminal#23]
add a feature to pull the color scheme from the currently used theme inside of emacs. This could be a boolean variable

**Comment by mumu-lhl** [comment]
This is not possible. Because the theme is implemented by changing the _face_, not the color of the colour name, and a given _face_ doesn't always have to be a color.

You can look up the theme you're using at https://github.com/mbadolato/iTerm2-Color-Schemes and modify `eaf-pyqterminal-color-schema`

**Comment by Dou2ble** [comment]
Yes but instead you could get the color from the "term-color" faces.
